### ISSUE TITLE
Implementation using REST instead of HTTP API

### ISSUE THREAD

**Issue by saif-ellafi** [amancevice/terraform-aws-serverless-pypi#11]
Hi there! Thanks again for this repo

After some time, decided to try on my environment, and in order to have more power on the control of intranet vpc endpoints and other [access control features](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html), the REST API Gateway is more powerful than the HTTP API Gateway.

After some testing, it works almost out of the box, but the lambda function need a slight re-adjustment on this function:
from
```
def parse_payload(event):
    """
    Get HTTP request method/path/body for v2 payloads.
    """
    body = event.get('body')
    routeKey = event.get('routeKey')
    method, _ = routeKey.split(' ')
    try:
        package, *_ = event['pathParameters']['package'].split('/')
    except KeyError:
        package = None
    return (method, package, body)
```

to
```
def parse_payload(event):
    """
    Get HTTP request method/path/body for v2 payloads.
    """
    body = event.get('body')
    method = event.get('httpMethod')
    try:
        package, *_ = event['pathParameters']['package'].split('/')
    except (KeyError, TypeError):
        package = None
    return (method, package, body)
```

I don't have the time now but if this is of interest we could eventually make it work for both event content types (for http and rest modes)

best!

**Comment by amancevice** [comment]
There's a discussion about this in #5 — you should be able to test out a REST version by using the GitHub source URL with `ref=rest`

**Comment by saif-ellafi** [comment]
Moving over there! thanks
