### ISSUE TITLE
Private launch?

### ISSUE THREAD

**Issue by jorwoods** [amancevice/terraform-aws-serverless-pypi#5]
Great module! Have you had any success launching http api in a fashion that limits access to only from within a VPC? Or are we constricted to using something like cognito because of pypi's limited auth acceptance?

**Comment by amancevice** [comment]
I haven't personally done this, but at my last company we had a VPC that users could connect to via a local client, like Tunnel Blick, and this allowed users to hit certain endpoints that would otherwise be inaccessible.

We had an internal PyPI server that was secured this way, but it was running on ECS and not serverless like this. I left before I had a chance to deploy it :)

If it's not behind a VPC you're restricted to using Basic HTTP auth as `pip` can't really do anything fancier.

**Comment by jorwoods** [comment]
I will have to do some experimentation, but I wonder if a lambda authorizer would still work.

**Comment by amancevice** [comment]
Oh yeah definitely you could do that! The problem IMO is that because you are limited to Basic auth you need to have some kind of management over your users and their passwords. If someone was to leave the org, for instance you'd want to revoke their access. So while a Lambda would work you're only solving a small piece of the puzzle.

What would be great would be for pip to support some kind of request signing like AWS, but that seems like it's not happening any time soon.

**Comment by gijsdpg** [comment]
I came here to ask the same question, or at least I think :). We want our pypi service to be only accessible from a specific IP range, security group or VPC. I tried to configure this in the API gateway, but it seems this is only possible for the REST type, not for the HTTP type. This module seems to work with  HTTP API gateway only.

Thanks for this great module by the way :) makes setting up a pypi service almost flawless.

**Comment by amancevice** [comment]
wow TIL that HTTP APIs don't support private mode. Has this always been the case? I guess it's time to create a fork of this for REST APIs...

**Comment by jorwoods** [comment]
The lambda authorizer definitely works, and isn’t too complicated.

**Comment by jorwoods** [comment]
*Lambda authorized definitely worked for restricting access so that it works for our on prem applications. I have not yet tested to see if I can restrict access to only certain VPCs or SGs from within AWS

**Comment by amancevice** [comment]
@gijsdpg would you be willing to test a branch of this repo that supports REST? You can test it using the GitHub URL:

```terraform
module "serverless_pypi_rest" {
  source = "github.com/amancevice/terraform-aws-serverless-pypi?ref=rest"
  # …
}
```

**Comment by gijsdpg** [comment]
that's fast! thanks! unfortunately, i won't have time until Friday, I'll let you know as soon as I tried. thanks!

**Comment by saif-ellafi** [comment]
oh! I haven't tried the terraform build of the rest version, but creating the REST component manually, I still had to change the python code:

from
```
def parse_payload(event):
    """
    Get HTTP request method/path/body for v2 payloads.
    """
    body = event.get('body')
    routeKey = event.get('routeKey')
    method, _ = routeKey.split(' ')
    try:
        package, *_ = event['pathParameters']['package'].split('/')
    except KeyError:
        package = None
    return (method, package, body)
```

to
```
def parse_payload(event):
    """
    Get HTTP request method/path/body for v2 payloads.
    """
    body = event.get('body')
    method = event.get('httpMethod')
    try:
        package, *_ = event['pathParameters']['package'].split('/')
    except (KeyError, TypeError):
        package = None
    return (method, package, body)
```

**Comment by amancevice** [comment]
That exact change is made in the `rest` branch :)

**Comment by saif-ellafi** [comment]
Awesome! As always, I am a bit clumsy when proceeding :D

**Comment by gijsdpg** [comment]
I had some time to play with this, but didn't get it fully working yet.

my working terraform

https://gist.github.com/gijsdpg/61ce3ea6e8456841f8e52d98a1c6739c

which gives the errors:

```
╷
│ Error: Error creating API Gateway Deployment: BadRequestException: No integration defined for method
│
│   with aws_api_gateway_deployment.pypi,
│   on apigateway_rest.tf line 25, in resource "aws_api_gateway_deployment" "pypi":
│   25: resource "aws_api_gateway_deployment" "pypi" {
│
╵
╷
│ Error: Error creating API Gateway Domain Name: BadRequestException: Cannot import certificates for REGIONAL while EDGE is active.
│
│   with aws_api_gateway_domain_name.pypi,
│   on apigateway_rest.tf line 54, in resource "aws_api_gateway_domain_name" "pypi":
│   54: resource "aws_api_gateway_domain_name" "pypi" {
│
╵
╷
│ Error: Error creating API Gateway Method: ConflictException: Method already exists for this resource
│
│   with module.serverless_pypi.aws_api_gateway_method.root_get,
│   on .terraform/modules/serverless_pypi/main.tf line 330, in resource "aws_api_gateway_method" "root_get":
│  330: resource "aws_api_gateway_method" "root_get" {
```

this is probably a mistake on my side, but I'm out of time. going to have a look again next week.

**Comment by gijsdpg** [comment]
I realize now I was overthinking this whole thing and I see your module already implements all methods :) Awesome.

I can apply the code with this simple tf:

https://gist.github.com/gijsdpg/0a54db5a1585adbd6f6a331a9e3e8695

but I keep on getting a `{"message":"Forbidden"}` on `/`. I did not configure any ACLs yet, and oddly enough it does seem like the calls arrive at the lambda, which returns an index. I keep on debugging, but if you have a suggestion I'm all ears.

**Comment by IdrisMiles** [comment]
I would also be very interested in being able to run this from a REST api gateway so that it can be run as a private api within our VPC. Just curious if there was anymore progress on this?

**Comment by amancevice** [comment]
@IdrisMiles thanks for the reminder. I just updated the REST branch of this repo with some fixes and improvements. Would you be willing to try it? check the example folder in the branch for usage.

**Comment by IdrisMiles** [comment]
Thanks @amancevice , yep will try give it a test over the next week

**Comment by IdrisMiles** [comment]
@amancevice have got round to giving this a test now.

When I first set this up, doing pip installs was failing due to issues with the signed S3 URL. When following the S3 URL I was getting the following:
(not too sure what should/shouldn't be shown publicly here, so have obscured a few bits from the response)
```xml
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<AWSAccessKeyId>...</AWSAccessKeyId>
<StringToSign>AWS4-HMAC-SHA256 20230312T194514Z 20230312/eu-west-2/s3/aws4_request f458fc9ccf6ebd5c97d6747bf49a1f3e6a714d9029a1929bc7a45aa92be38a38</StringToSign>
<SignatureProvided>...</SignatureProvided>
<StringToSignBytes>...</StringToSignBytes>
<CanonicalRequest>GET /sparro-services/sparro_services-0.0.1-py3-none-any.whl X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...%2F20230312%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230312T194514Z&X-Amz-Expires=900&X-Amz-Security-Token=...&X-Amz-SignedHeaders=host host:my-s3-bucket-eu-west-2.s3.eu-west-2.amazonaws.com host UNSIGNED-PAYLOAD</CanonicalRequest>
<CanonicalRequestBytes>.....</CanonicalRequestBytes>
<RequestId>MB8F29T7PBSQ23NF</RequestId>
<HostId>VBvQsAM6krnaC2zAz+qG+rz0LnUg8lBZeQR3rkpEVegZdTDFqOkRjWAQb/4lI1tKQpqo7qlY8QI=</HostId>
</Error>
```

However after 24 hours, trying again, pip install is now working...
Not sure if there are any quirks with S3 signed URLs and newly created buckets/objects?

Will continue testing over the next few days, but so far seems to be working now.

I've setup the rest api as `PRIVATE` rather than `REGIONAL`, in case anyone else is interested you need to make the following tweaks to the api gateway terraform:

```terraform
resource "aws_api_gateway_rest_api" "pypi" {
  description = "Serverless PyPI example"
  name        = "serverless-pypi"

  # for private APIs
  endpoint_configuration {
    types            = ["PRIVATE"]
    vpc_endpoint_ids = [var.VPCE_ID]
  }
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : "*",
        "Action" : "execute-api:Invoke",
        "Resource" : "arn:*:execute-api:*:*:*",
        "Condition" : {
          "StringEquals" : {
            "aws:SourceVpce" : var.VPCE_ID
          }
        }
      }
    ]
  })
}
```

**Comment by amancevice** [comment]
@IdrisMiles I can't think of any reason for needing a warm-up time for new buckets/objects to work other than maybe 5m just to ensure all the IAM stuff flows through. Anyway, cool that it's working for now. I'll wait to hear for any issues and then maybe cut over to a new major version of this tool.

**Comment by IdrisMiles** [comment]
Just reporting back that so far this has been stable for me. I think my earlier issues must be related to the bucket being new, haven't been able to re-create the issue.

**Comment by amancevice** [comment]
cool, I'll cut a new major version as soon as I get the chance

**Comment by amancevice** [comment]
OK, I have released [v7](https://github.com/amancevice/terraform-aws-serverless-pypi/releases/tag/v7.0.0) with a few more minor changes: I got rid of the Lambda aliases as unnecessary complexity and changed the S3 notification to use EventBridge instead of SNS
