### ISSUE TITLE
apply requires ARN but then tries to create the lambda?

### ISSUE THREAD

**Issue by saif-ellafi** [amancevice/terraform-aws-serverless-pypi#7]
Hi, thanks for doing this.
I am running this on a testing environment with `terraform apply` however the first requested variable is the ARN of the execution trigger `var.api_execution_arn` between the API Gateway and Lambda. In order to get this ARN I have to create both the API Gateway and set its target to a Lambda function which I also create. Once they are linked, I can get such ARN. But then Terraform script fails as it tries to create the lambda function I had to create in order to get the execute ARN. Am I doing something wrong or is there a logical gap?

`Error: error creating Lambda Function (1): ResourceConflictException: Function already exist: pypi_lambda_inbound`

Thanks again!

**Comment by amancevice** [comment]
I think you are confusing the Lambda execution ARN and the API Gateway execution ARN. 

The README gives an example, but the short of it is that you are expected to create an API Gateway resource on your own (there are too many different ways to configure it to be viable in a module). You then pass the ID and execution ARN attributes of the API Gateway to the module

Eg

```terraform

resource "aws_apigatewayv2_api" "pypi" {
  name          = "pypi"
  protocol_type = "HTTP"
}

module "serverless_pypi" {
  # ...

  api_id                       = aws_apigatewayv2_api.pypi.id
  api_execution_arn            = aws_apigatewayv2_api.pypi.execution_arn
  
  # ...
}

```

**Comment by saif-ellafi** [comment]
Thanks, I am still confused. Where am I supposed to get the API Gateway execution ARN from?
When I create the API Gateway, it only has an ID.
I only see an execution ARN once I link the Gateway to Lambda, not before. Right?

Will keep checking on the meantime to figure it out :)

**Comment by amancevice** [comment]
Check out the attributes of API Gateway v2 API: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_api#attributes-reference

**Comment by amancevice** [comment]
You don't have to know the execution ARN you just pass the reference to it to the module, something like `aws_apigatewayv2_api.<your-api>.execution_arn`

**Comment by saif-ellafi** [comment]
ahh gotcha! 👍🏻 not the ARN but literally the ARN prefix to be used. Thanks for the clarification, I was not even close to figuring this out. Following some docs I got to build the execution arn myself following this convention: 

`arn:aws:execute-api:<region>:<account-id>:<api-id>`

**Comment by amancevice** [comment]
yeah it's just something used to ensure the Lambda has all the right permissions to be invoked by API Gateway.

That said, you shouldn't have to build the ARN yourself — that sounds like asking for trouble to me. If you're trying to reference an API from another project you could use a data resource:

```terraform
data "aws_apigatewayv2_api" "pypi" {
  api_id = "<your-api-id>"
}

module "serverless_pypi" {
  # ...

  api_id            = data.aws_apigatewayv2_api.pypi.id
  api_execution_arn = data.aws_apigatewayv2_api.pypi.execution_arn
  
  # ...
}
```

**Comment by saif-ellafi** [comment]
No no, not trying to reference it. I am just trying to directly `apply` it on my personal environment. Terraform offers a "wizard-like" walkthrough asking for all undefined variables. This `execution_arn` seems to be a terraform construct, not a value I can take from AWS. So for this case, setting myself that value seems just fine.

**Comment by saif-ellafi** [comment]
Ok, nevermind me. I saw the error in my ways. Running it as a module as an extension to your remote version, as normal people do, and letting the `execution_arn` come from terraform. I got distracted by figuring out where that value actually came from. This issue may be confusing for other people.

**Comment by amancevice** [comment]
haha no worries — we've all been there. happy to answer any other questions if they come up.
