### ISSUE TITLE
Not making it work through pip install

### ISSUE THREAD

**Issue by saif-ellafi** [amancevice/terraform-aws-serverless-pypi#8]
Everything seems to be working fine, the indexer triggers on new s3 files, and a get request returns the contents of the index file correctly.

I created a stage manually for the API Gateway called `simple` in order to fulfill the pep standard

Yet when I call from pip
```pip3 install --index-url https://myapi.amazonaws.com/simple/ my-pkg```
I get
```
Defaulting to user installation because normal site-packages is not writable
Looking in indexes: https://myapi.amazonaws.com/simple/
ERROR: Could not find a version that satisfies the requirement my-pkg (from versions: none)
ERROR: No matching distribution found for my-pkg
```

The path to `/simple/my-pkg` does generate a page with temporary S3 links, so I am out of ideas now :/ 

What could be wrong? Any help welcome
Thanks!

**Comment by amancevice** [comment]
what's the output of `curl https://myapi.amazonaws.com/simple/`?

**Comment by saif-ellafi** [comment]
```
saif@Saifs-MBP example-package % curl https://myapi.amazonaws.com/simple/      
<!DOCTYPE html><html><head><title>Simple index</title></head><body><h1>Simple index</h1><a href="my-pkg">my-pkg</a><br></body></html>% 
´´´

**Comment by amancevice** [comment]
Does `curl https://myapi.amazonaws.com/simple/my-pkg`? return HTML?

(Don't paste the output without removing the presigned URL)

**Comment by saif-ellafi** [comment]
Haha, I was trying to obfuscate it. But if "works" is enough, I get a huge link. What surprises me is the domain of the URL, it is literally the bucketname amazonaws.com. I'll see how to obfuscate it securely

**Comment by saif-ellafi** [comment]
btw. Copy pasting the link within `href` doesn't work, but when I access through the browser, stuff seems fine.

**Comment by amancevice** [comment]
I think I might know what the issue is — Looking into it now...

**Comment by saif-ellafi** [comment]
Here entire message (payload continues with keys and signing codes)
```
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
```

**Comment by saif-ellafi** [comment]
Switching to `$default` as stage for apigateway doesn't seem to help.

**Comment by amancevice** [comment]
ok, I just pushed a change — can you try using version `4.1.1` of the module?

**Comment by saif-ellafi** [comment]
sure thing, will check it out when you give the signal :)

**Comment by amancevice** [comment]
ok, please try again with module version `4.1.2`

**Comment by saif-ellafi** [comment]
Ah, it looks like its about to start before it gives an error 403
```ERROR: HTTP error 403 while getting <long-url> ERROR: Could not install requirement my-pkg from <long-url> error 403 Client Error: Forbidden for url: <long-url>

(this is not the cognito version btw) - also exporting aws credentials doesn't help (not even sure if that should even make any difference) when calling the http from terminal.

**Comment by saif-ellafi** [comment]
Oh I believe I made it work. Created a `simple` stage from previous `$default` one, emptied bucket and uploaded packages again.

**Comment by amancevice** [comment]
ah yeah so if you had omitted `/simple` from your index URL that would have worked too. Using a stage is fine; you could also attach the default stage of the API to a custom domain at `/simple`. Plenty of ways to skin a cat!

**Comment by saif-ellafi** [comment]
Thanks! Wasn't lucky with the Cognito version yet. The endpoint not triggering the lambda behind the authorizer. So let see. Lot's of learning already. Thanks for your patience! Awesome repo.

**Comment by amancevice** [comment]
sounds good — let me know if you run into issues
